version: "3.7"
services:
  auth:
    build: .
    depends_on:
      - mongodb
    environment:
      AUTH_HEADER: X-User-ID
      COOKIE_DOMAIN: localhost
      COOKIE_DURATION: 24h
      COOKIE_NAME: auth_cookie
      COOKIE_SECRET: 7NadWLuKdzNJQSLL
      DB_COLLECTION: users
      DB_HOST: mongodb:27017
      DB_NAME: primary
      DB_PASSWORD: password
      DB_USERNAME: root
      DEBUG: true
      DOMAIN: http://localhost:8080/
      PORT: "80"
    env_file:
      - secrets.env
    links:
      - mongodb
    ports:
      - 8080:80
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: primary
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_USERNAME: root
    ports:
      - "27017:27017"
